DROP TABLE CARRERAS;
DROP TABLE ULTNUM;
DROP TABLE USUARIO;
DROP TABLE GALGOS;
DROP SEQUENCE SEQ_ULTNUM;

CREATE TABLE USUARIO (
    CORREO VARCHAR2(255),
    NOMBRE_USUARIO VARCHAR2(50),
    CONTRASENA VARCHAR2(50),
    NOMBRE_REAL VARCHAR2(50),
    APELLIDO1 VARCHAR2(50),
    APELLIDO2 VARCHAR2(50),
    SALDO NUMBER,
    CONSTRAINT PK_USUARIO PRIMARY KEY (CORREO)
);


CREATE TABLE CARRERAS (
    ID NUMBER,
    CIUDAD VARCHAR2(50),
    HORA VARCHAR2(50),
    ESTADO VARCHAR2(50),
    CONSTRAINT PK_CARRERAS PRIMARY KEY (ID)
);

CREATE TABLE GALGOS (
    NOMBRE VARCHAR2(50),
    COLOR VARCHAR2(50),
    NUMERO NUMBER,
    EXPERIENCIA NUMBER,
    ACELERACION NUMBER,
    VELOCIDAD NUMBER,
    CUOTA NUMBER,
    APOSTADO NUMBER,
    FINCARRERA NUMBER,
    CONSTRAINT PK_GALGOS PRIMARY KEY (NOMBRE)
);


CREATE TABLE ULTNUM (
    ID NUMBER,
    NUMERO NUMBER,
    CONSTRAINT PK_ULTNUM PRIMARY KEY (ID)
);


CREATE SEQUENCE SEQ_ULTNUM
START WITH 11
INCREMENT BY 1
MAXVALUE 9999999999999999999
MINVALUE 1
NOCACHE
NOCYCLE;


INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Okupa', NULL, 47, 6, 3, 9, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Chopper', NULL, 20, 7, 4, 2, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Agallas', NULL, 81, 1, 7, 5, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Garfield', NULL, 59, 4, 6, 8, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Snoopy', NULL, 15, 5, 8, 1, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Scooby', NULL, 36, 2, 5, 7, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Brian', NULL, 73, 9, 1, 4, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Odie', NULL, 68, 1, 9, 6, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Perry', NULL, 42, 8, 2, 3, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Pluto', NULL, 91, 6, 4, 5, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Dug', NULL, 18, 3, 7, 2, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Pochita', NULL, 55, 7, 3, 8, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Akamaru', NULL, 77, 8, 8, 1, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Nevado', NULL, 29, 5, 1, 9, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Arcanine', NULL, 63, 6, 6, 4, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Kurama', NULL, 44, 9, 5, 3, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Firulais', NULL, 87, 4, 2, 6, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Ok', NULL, 39, 8, 9, 7, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Pascualin', NULL, 72, 3, 4, 5, 0, 0, 0);
INSERT INTO GALGOS (NOMBRE, COLOR, NUMERO, EXPERIENCIA, ACELERACION, VELOCIDAD, CUOTA, APOSTADO, FINCARRERA) VALUES ('Canelita', NULL, 50, 7, 6, 1, 0, 0, 0);

INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (1, 'Paris', '12:00', 'Finalizada');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (2, 'Londres', '13:00', 'Finalizada');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (3, 'Madrid', '15:00', 'Finalizada');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (4, 'Barcelona', '17:00', 'Proxima');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (5, 'Sevilla', '18:30', 'Espera');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (6, 'Valencia', '16:45', 'Espera');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (7, 'Bilbao', '19:00', 'Espera');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (8, 'Zaragoza', '20:15', 'Espera');
INSERT INTO CARRERAS (ID, CIUDAD, HORA, ESTADO) VALUES (9, 'Málaga', '21:30', 'Espera');


INSERT INTO ULTNUM (ID, NUMERO) VALUES(1, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(2, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(3, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(4, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(5, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(6, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(7, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(8, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(9, TRUNC(DBMS_RANDOM.VALUE(0, 37)));
INSERT INTO ULTNUM (ID, NUMERO) VALUES(10, TRUNC(DBMS_RANDOM.VALUE(0, 37)));


INSERT INTO USUARIO (CORREO, NOMBRE_USUARIO, CONTRASENA, NOMBRE_REAL, APELLIDO1, APELLIDO2, SALDO) VALUES ('pablo@pablo.com', 'asd', 'asd', 'asd', 'asd', 'asd', 0);
INSERT INTO USUARIO (CORREO, NOMBRE_USUARIO, CONTRASENA, NOMBRE_REAL, APELLIDO1, APELLIDO2, SALDO) VALUES ('am291092@gmail.com', 'asd', 'asd', 'asddas', 'asd', 'asd', 10);
INSERT INTO USUARIO (CORREO, NOMBRE_USUARIO, CONTRASENA, NOMBRE_REAL, APELLIDO1, APELLIDO2, SALDO) VALUES ('jose@jose.com', 'asd', 'asd', 'asdas', 'asd', 'asd', 21936);
INSERT INTO USUARIO (CORREO, NOMBRE_USUARIO, CONTRASENA, NOMBRE_REAL, APELLIDO1, APELLIDO2, SALDO) VALUES ('usuario@nuevo.com', 'usuario', 'usuario', 'asda', 'asd', 'sd', 13577);

